version: 2

shared: &shared
  working_directory: ~/repo
  docker:
    - image: docker:18.09.2
  steps:
    - checkout
    - setup_remote_docker
    - run:
        name: build image
        command: |
          docker build -f test/Dockerfile --build-arg RUBY_VERSION -t honestica/clamav-client .
    - run:
        name: run tests
        command: |
          docker run honestica/clamav-client rake

jobs:
  "2.7":
    <<: *shared
    environment:
      RUBY_VERSION=2.7-slim
  "3.2":
    <<: *shared
    environment:
      RUBY_VERSION=3.2-slim

workflows:
  version: 2
  build:
    jobs:
      - "2.7"
      - "3.2"